### ISSUE TITLE
integrate first set of rules.

### ISSUE THREAD

**Issue by nikhilkmr** [nikhilkmr/esantepmd#2]

**Comment by nikhilkmr** [comment]
@nishthanegi06 for rule : remove and removeAll of List is forbidden, use below XPath : 
`//StatementExpression/PrimaryExpression
[
    PrimaryPrefix
    [
        ./Name[ends-with(@Image, '.remove') or @Image = 'remove' 
or ends-with(@Image, '.removeAll') or @Image = 'removeAll']
        and substring-before(Name/@Image, '.') =//VariableDeclarator/VariableDeclaratorId/@Image
        [../../../Type/ReferenceType[ClassOrInterfaceType[@Image = 'List' or @Image = 'ArrayList' or @Image = 'Vector']]]
        or (
        ./AllocationExpression/ClassOrInterfaceType[@Image = 'List' or @Image = 'ArrayList'  or @Image = 'Vector']
        and ../PrimarySuffix[@Image = 'remove' or @Image = 'removeAll'])
    ]
]`

**Comment by nikhilkmr** [comment]
@nishthanegi06 I am attaching ruleset for refrence, take help from it.
[pmd_ruleset.zip](https://github.com/nikhilkmr/esantepmd/files/1748907/pmd_ruleset.zip)

**Comment by nishthanegi06** [comment]
@nikhilkmr sir i have added all the xpaths in the rule set, kindly review those and let me know in case of any issue.

**Comment by nikhilkmr** [comment]
same has been done. and merged to head.
